### PR TITLE
Controll over initialization and Documentaion update

### PR DESCRIPTION
**Pull request by Niremizov**
Previously I have created issues about "Controll over initialization" and documentation update, and here is a fork for this.

### CODE REVIEW

**Comment by nezhelskoy** [comment]
Ok, you have convinced me of the need of these methods. But it does not refer to "DI", please remove or change comments "Required setter by Yii's Dependency Injection to work properly.". Then I will be able to merge your pull request.
Thanks for useful improvements.

**Comment by nezhelskoy** [comment]
As I understand it - these methods simply give support configurable [properties](https://github.com/yiisoft/yii2/blob/master/docs/guide/concept-properties.md).

**Comment by Niremizov** [comment]
Commit 2cb3673f5d7da0aadd74a3fe25569bacbafcbdda

**Comment by Niremizov** [comment]
> Thanks for useful improvements.
> - nezhelskoy

Не за что!

**Pull request merged**
